### PR TITLE
CacheModel needs expiresAt to be a long in Elasticsearch

### PR DESCRIPTION
**Pull request by ZachRoberts25**
...

### CODE REVIEW

**Comment by ZachRoberts25** [comment]
ok I also made changes in convert raw response where the es apis just returned slightly different responses and its easier to do it this way.  Let me know what you think

**Comment by ZachRoberts25** [comment]
any update on this?  Needed for us to upgrade to 1.0

**Comment by arciisine** [comment]
Fell off my radar.  Will get this out tonight

**Comment by arciisine** [comment]
Should be resolved with latest builds.  Take a look at the code change if you want see what I ultimately did.

**Comment by ZachRoberts25** [comment]
what about the changes I made to convert raw response ?  Those get lose in this ?  Otherwise the change looks good

**Comment by arciisine** [comment]
Missed that, will solve that in another PR tonight

**Comment by arciisine** [comment]
So, looking at the change, the current code `execSearch` only returns the `SearchResponse`, not the the `es.ApiResponse`.  This would need to be updated to match, and so I want to make sure it's helpful.  What in the `es.ApiResponse` do you need outside of body?

**Comment by ZachRoberts25** [comment]
I just needed to update stuff on my side.  Feel free to close

**Pull request closed without merging**
